### ISSUE TITLE
Handling on( 'change')

### ISSUE THREAD

**Issue by alexTitakoff** [lonlie/select2tree#11]
Hello!

Can I put the handlers on you version select2?
because I want to watch the state of the component.

like this. This is a standard call to handlers
http://snpy.in/udc0BO  (code example)
`$(this.$el).select2({
                data: this.someFunc(),
            }).val(this.value)
                .trigger('change')              
                .on('change', function () {                             // emit event on change.
                    vm.$emit('update:input', $(this).val())
                    vm.$emit('select-handler', $(this).val())})
               `

Thanks you

**Comment by lonlie** [comment]
Of course, you can add pull request. Thanks!
